[package]
name = "Website_Checker"
version = "0.1.0"
edition = "2024"

[dependencies]
ureq = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
